export const Users = [
  {
    id:1,
    profilePicture: "assets/person/deyane.jpg",
    username: "Mohameed Deyane",
  },
  {
    id:2,
    profilePicture: "assets/person/farhan.jpg",
    username: "Ayoub Farhan",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/person/8.jpeg",
    username: "Salma El-Massoudi",
  },
  {
    id:5,
    profilePicture: "assets/person/ideriss.jpg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/0.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/post/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/post/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/fatima.jpg",
    username: "Fatima Fati",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "My Best Anime.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "My Best Food.",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Whit My Sester.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Good Morning.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Beautifle day whit my love.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "My Love :)",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 1204,
    comment: 12,
  },
  // {
  //   id: 11,
  //   photo: "assets/post/10.jpeg",
  //   date: "1 week ago",
  //   userId: 11,
  //   like: 14,
  //   comment: 12,
  // },
];

export const Video = [
  {
    id: 1,
    video: "assets/post/vid.mp4",
    date: "1 week ago",
    userId: 1,
    liked: 2104,
    comment: 112,
  },
];
